services:

  db:
    image: postgres:16
    container_name: trello_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: trello_db
      POSTGRES_USER: trello_user
      POSTGRES_PASSWORD: trello_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: trello_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: trello_web
    restart: unless-stopped
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=clave-secreta-cambiar-en-produccion
      - DB_NAME=trello_db
      - DB_USER=trello_user
      - DB_PASSWORD=trello_pass
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
